from typing import List

import pytest
import src


@pytest.mark.parametrize(
    # NOTE you need more complex examples to test all scenarios
    "test_input, expected_len, expected_arr",
    [
        (["a", "a", "b", "b", "c", "c", "c"], 6, ["a", "2", "b", "2", "c", "3"]),
        (["a"], 1, ["a"]),
        (
            [
                "p",
                "p",
                "p",
                "p",
                "m",
                "m",
                "b",
                "b",
                "b",
                "b",
                "b",
                "u",
                "u",
                "r",
                "r",
                "u",
                "n",
                "n",
                "n",
                "n",
                "n",
                "n",
                "n",
                "n",
                "n",
                "n",
                "n",
                "u",
                "u",
                "u",
                "u",
                "a",
                "a",
                "u",
                "u",
                "r",
                "r",
                "r",
                "s",
                "s",
                "a",
                "a",
                "y",
                "y",
                "y",
                "g",
                "g",
                "g",
                "g",
                "g",
            ],
            30,
            [
                "p",
                "4",
                "m",
                "2",
                "b",
                "5",
                "u",
                "2",
                "r",
                "2",
                "u",
                "n",
                "1",
                "1",
                "u",
                "4",
                "a",
                "2",
                "u",
                "2",
                "r",
                "3",
                "s",
                "2",
                "a",
                "2",
                "y",
                "3",
                "g",
                "5",
            ],
        ),
        (
            ["a", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b", "b"],
            4,
            ["a", "b", "1", "2"],
        ),
    ],
)
def test_compress(test_input: List[str], expected_len: int, expected_arr: [str]):
    assert src.Solution().compress(test_input) == (expected_len, expected_arr)


if __name__ == "__main__":
    test_compress()
